// <auto-generated />

using System;

using AngularNetBase.Practice.Infrastructure;

using Microsoft.EntityFrameworkCore;

using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;


using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL;


using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;



#nullable disable



namespace AngularNetBase.Practice.Infrastructure.Migrations

{

    [DbContext(typeof(PracticeContext))]
    [Migration("20260413174500_RemovePracticeVersionColumns")]

    partial class RemovePracticeVersionColumns : Migration

    {

        protected override void BuildTargetModel(ModelBuilder modelBuilder)

        {

#pragma warning disable 612, 618

            modelBuilder

                .HasDefaultSchema("practice")

                .HasAnnotation("ProductVersion", "10.0.3")

                .HasAnnotation("Relational:MaxIdentifierLength", 63);



            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);



            modelBuilder.Entity("AngularNetBase.Practice.Entities.AffirmationValues.AffirmationValue", b =>

                {

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");



                    b.Property<string>("Name")

                        .IsRequired()

                        .HasMaxLength(200)

                        .HasColumnType("character varying(200)");






                    NpgsqlModelBuilderExtensions.UseXminAsConcurrencyToken(b);

                    b.HasKey("Id");



                    b.ToTable("AffirmationValues", "practice");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.AffirmationValues.ValueStatement", b =>

                {

                    b.Property<Guid>("Id")

                        .ValueGeneratedOnAdd()

                        .HasColumnType("uuid");



                    b.Property<Guid>("AffirmationValueId")

                        .HasColumnType("uuid");



                    b.Property<bool>("IsActive")

                        .HasColumnType("boolean");



                    b.Property<string>("Text")

                        .IsRequired()

                        .HasMaxLength(1000)

                        .HasColumnType("character varying(1000)");






                    NpgsqlModelBuilderExtensions.UseXminAsConcurrencyToken(b);

                    b.HasKey("Id");



                    b.HasIndex("AffirmationValueId");



                    b.ToTable("ValueStatements", "practice");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.DistancedJournals.DistancedJournalChallenge", b =>

                {

                    b.Property<Guid>("Id")

                        .ValueGeneratedOnAdd()

                        .HasColumnType("uuid");



                    b.Property<string>("ChallengeLevel")

                        .IsRequired()

                        .HasMaxLength(20)

                        .HasColumnType("character varying(20)");



                    b.Property<string>("Content")

                        .IsRequired()

                        .HasMaxLength(2000)

                        .HasColumnType("character varying(2000)");



                    b.Property<string>("FollowUpQuestion")

                        .IsRequired()

                        .HasMaxLength(1000)

                        .HasColumnType("character varying(1000)");






                    NpgsqlModelBuilderExtensions.UseXminAsConcurrencyToken(b);

                    b.HasKey("Id");



                    b.ToTable("DistancedJournalChallenges", "practice");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.DistancedJournals.DistancedJournalExercise", b =>

                {

                    b.Property<Guid>("Id")

                        .ValueGeneratedOnAdd()

                        .HasColumnType("uuid");



                    b.Property<Guid>("ChallengeId")

                        .HasColumnType("uuid");



                    b.Property<Guid>("UserId")

                        .HasColumnType("uuid");






                    NpgsqlModelBuilderExtensions.UseXminAsConcurrencyToken(b);

                    b.HasKey("Id");



                    b.HasIndex("UserId", "ChallengeId");



                    b.ToTable("DistancedJournalExercises", "practice");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.GrowthMessages.GrowthMessage", b =>

                {

                    b.Property<Guid>("Id")

                        .ValueGeneratedOnAdd()

                        .HasColumnType("uuid");



                    b.Property<bool>("IsActive")

                        .HasColumnType("boolean");



                    b.Property<string>("Text")

                        .IsRequired()

                        .HasMaxLength(1000)

                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");


                    NpgsqlModelBuilderExtensions.UseXminAsConcurrencyToken(b);

                    b.HasKey("Id");

                    b.ToTable("GrowthMessages", "practice");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.PerspectiveScenarios.PerspectiveScenarioChallenge", b =>

                {

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActorCount")
                        .HasColumnType("integer");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");



                    b.Property<string>("ChallengeLevel")

                        .IsRequired()

                        .HasMaxLength(20)

                        .HasColumnType("character varying(20)");



                    b.Property<string>("Reveal")

                        .IsRequired()

                        .HasMaxLength(2000)

                        .HasColumnType("character varying(2000)");



                    b.Property<string>("ScenarioText")

                        .IsRequired()

                        .HasMaxLength(2000)

                        .HasColumnType("character varying(2000)");






                    NpgsqlModelBuilderExtensions.UseXminAsConcurrencyToken(b);

                    b.HasKey("Id");



                    b.ToTable("PerspectiveScenarioChallenges", "practice");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.PerspectiveScenarios.PerspectiveScenarioExercise", b =>

                {

                    b.Property<Guid>("Id")

                        .ValueGeneratedOnAdd()

                        .HasColumnType("uuid");



                    b.Property<Guid>("ChallengeId")

                        .HasColumnType("uuid");



                    b.Property<DateTime?>("SubmittedAt")

                        .HasColumnType("timestamp with time zone");



                    b.Property<Guid>("UserId")

                        .HasColumnType("uuid");






                    NpgsqlModelBuilderExtensions.UseXminAsConcurrencyToken(b);

                    b.HasKey("Id");



                    b.HasIndex("UserId", "ChallengeId");



                    b.ToTable("PerspectiveScenarioExercises", "practice");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.PerspectiveScenarios.PerspectiveScenarioQuestion", b =>

                {

                    b.Property<Guid>("Id")

                        .ValueGeneratedOnAdd()

                        .HasColumnType("uuid");



                    b.Property<Guid>("PerspectiveScenarioChallengeId")

                        .HasColumnType("uuid");



                    b.Property<string>("QuestionText")

                        .IsRequired()

                        .HasMaxLength(1000)

                        .HasColumnType("character varying(1000)");



                    b.Property<Guid>("SkillId")

                        .HasColumnType("uuid");






                    NpgsqlModelBuilderExtensions.UseXminAsConcurrencyToken(b);

                    b.HasKey("Id");



                    b.HasIndex("PerspectiveScenarioChallengeId");



                    b.ToTable("PerspectiveScenarioQuestions", "practice");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.Scheduling.DailyChallengeAssignment", b =>

                {

                    b.Property<Guid>("Id")

                        .ValueGeneratedOnAdd()

                        .HasColumnType("uuid");



                    b.Property<DateTime>("AssignedAt")

                        .HasColumnType("timestamp with time zone");



                    b.Property<DateTime>("Date")

                        .HasColumnType("date");



                    b.Property<Guid>("DistancedJournalChallengeId")

                        .HasColumnType("uuid");



                    b.Property<Guid>("DistancedJournalChallengeId2")

                        .HasColumnType("uuid");



                    b.Property<Guid>("PerspectiveScenarioChallengeId")

                        .HasColumnType("uuid");



                    b.Property<Guid>("PerspectiveScenarioChallengeId2")

                        .HasColumnType("uuid");



                    b.HasKey("Id");



                    b.HasIndex("Date")

                        .IsUnique();



                    b.ToTable("DailyChallengeAssignments", "practice");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.Sessions.DailySession", b =>

                {

                    b.Property<Guid>("Id")

                        .ValueGeneratedOnAdd()

                        .HasColumnType("uuid");



                    b.Property<DateTime>("Date")

                        .HasColumnType("date");



                    b.Property<string>("Status")

                        .IsRequired()

                        .HasMaxLength(20)

                        .HasColumnType("character varying(20)");



                    b.Property<Guid>("UserId")

                        .HasColumnType("uuid");






                    NpgsqlModelBuilderExtensions.UseXminAsConcurrencyToken(b);

                    b.HasKey("Id");



                    b.HasIndex("UserId", "Date")

                        .IsUnique();



                    b.ToTable("DailySessions", "practice");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.Sessions.SessionEvent", b =>

                {

                    b.Property<Guid>("Id")

                        .ValueGeneratedOnAdd()

                        .HasColumnType("uuid");



                    b.Property<Guid>("DailySessionId")

                        .HasColumnType("uuid");



                    b.Property<string>("Discriminator")

                        .IsRequired()

                        .HasMaxLength(13)

                        .HasColumnType("character varying(13)");



                    b.Property<DateTime>("Timestamp")

                        .HasColumnType("timestamp with time zone");



                    b.HasKey("Id");



                    b.HasIndex("DailySessionId");



                    b.ToTable("SessionEvents", "practice");



                    b.HasDiscriminator<string>("Discriminator").HasValue("SessionEvent");



                    b.UseTphMappingStrategy();

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.Skills.Skill", b =>

                {

                    b.Property<Guid>("Id")

                        .ValueGeneratedOnAdd()

                        .HasColumnType("uuid");



                    b.Property<string>("Description")

                        .IsRequired()

                        .HasMaxLength(1000)

                        .HasColumnType("character varying(1000)");



                    b.Property<string>("Name")

                        .IsRequired()

                        .HasMaxLength(200)

                        .HasColumnType("character varying(200)");






                    NpgsqlModelBuilderExtensions.UseXminAsConcurrencyToken(b);

                    b.HasKey("Id");



                    b.ToTable("Skills", "practice");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.Skills.SkillMastery", b =>

                {

                    b.Property<Guid>("Id")

                        .ValueGeneratedOnAdd()

                        .HasColumnType("uuid");



                    b.Property<int>("CurrentLevel")

                        .HasColumnType("integer");



                    b.Property<Guid>("SkillId")

                        .HasColumnType("uuid");



                    b.Property<Guid>("UserId")

                        .HasColumnType("uuid");






                    NpgsqlModelBuilderExtensions.UseXminAsConcurrencyToken(b);

                    b.HasKey("Id");



                    b.HasIndex("UserId", "SkillId")

                        .IsUnique();



                    b.ToTable("SkillMasteries", "practice");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.Sessions.ExerciseRecord", b =>

                {

                    b.HasBaseType("AngularNetBase.Practice.Entities.Sessions.SessionEvent");



                    b.Property<Guid>("ExerciseId")

                        .HasColumnType("uuid");



                    b.Property<string>("Type")

                        .IsRequired()

                        .HasMaxLength(50)

                        .HasColumnType("character varying(50)");



                    b.HasDiscriminator().HasValue("Exercise");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.Sessions.GeneralEvent", b =>

                {

                    b.HasBaseType("AngularNetBase.Practice.Entities.Sessions.SessionEvent");



                    b.Property<string>("EventType")

                        .IsRequired()

                        .HasMaxLength(100)

                        .HasColumnType("character varying(100)");



                    b.HasDiscriminator().HasValue("General");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.AffirmationValues.ValueStatement", b =>

                {

                    b.HasOne("AngularNetBase.Practice.Entities.AffirmationValues.AffirmationValue", null)

                        .WithMany("Statements")

                        .HasForeignKey("AffirmationValueId")

                        .OnDelete(DeleteBehavior.Cascade)

                        .IsRequired();

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.DistancedJournals.DistancedJournalExercise", b =>

                {

                    b.OwnsOne("AngularNetBase.Practice.Entities.DistancedJournals.DistancedJournalAnswer", "Answer", b1 =>

                        {

                            b1.Property<Guid>("DistancedJournalExerciseId")

                                .HasColumnType("uuid");



                            b1.Property<string>("FollowUpAnswer")

                                .HasMaxLength(3000)

                                .HasColumnType("character varying(3000)")

                                .HasColumnName("FollowUpAnswer");



                            b1.Property<string>("MainAnswer")

                                .HasMaxLength(3000)

                                .HasColumnType("character varying(3000)")

                                .HasColumnName("MainAnswer");



                            b1.Property<string>("Reflection")

                                .HasMaxLength(3000)

                                .HasColumnType("character varying(3000)")

                                .HasColumnName("Reflection");



                            b1.Property<DateTime>("SubmittedAt")

                                .HasColumnType("timestamp with time zone")

                                .HasColumnName("SubmittedAt");



                            b1.HasKey("DistancedJournalExerciseId");



                            b1.ToTable("DistancedJournalExercises", "practice");



                            b1.WithOwner()

                                .HasForeignKey("DistancedJournalExerciseId");

                        });



                    b.Navigation("Answer");

                });


            modelBuilder.Entity("AngularNetBase.Practice.Entities.DistancedJournals.DistancedJournalExercise", b =>

                {

                    b.OwnsMany("AngularNetBase.Practice.Entities.DistancedJournals.DistancedJournalPhoto", "Photos", b1 =>

                        {

                            b1.Property<Guid>("Id")

                                .ValueGeneratedOnAdd()

                                .HasColumnType("uuid");



                            b1.Property<string>("ContentType")

                                .IsRequired()

                                .HasMaxLength(100)

                                .HasColumnType("character varying(100)");



                            b1.Property<Guid>("DistancedJournalExerciseId")

                                .HasColumnType("uuid");



                            b1.Property<string>("FileName")

                                .IsRequired()

                                .HasMaxLength(255)

                                .HasColumnType("character varying(255)");



                            b1.Property<string>("ObjectKey")

                                .IsRequired()

                                .HasMaxLength(500)

                                .HasColumnType("character varying(500)");



                            b1.Property<long>("SizeBytes")

                                .HasColumnType("bigint");



                            b1.Property<DateTime>("UploadedAt")

                                .HasColumnType("timestamp with time zone");



                            b1.HasKey("Id");



                            b1.HasIndex("DistancedJournalExerciseId");



                            b1.ToTable("DistancedJournalPhotos", "practice");



                            b1.WithOwner()

                                .HasForeignKey("DistancedJournalExerciseId");

                        });



                    b.Navigation("Photos");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.PerspectiveScenarios.PerspectiveScenarioExercise", b =>

                {

                    b.OwnsMany("AngularNetBase.Practice.Entities.PerspectiveScenarios.ScenarioAnswer", "Answers", b1 =>

                        {

                            b1.Property<Guid>("Id")

                                .ValueGeneratedOnAdd()

                                .HasColumnType("uuid");



                            b1.Property<string>("AnswerText")

                                .IsRequired()

                                .HasMaxLength(3000)

                                .HasColumnType("character varying(3000)");



                            b1.Property<Guid>("PerspectiveScenarioExerciseId")

                                .HasColumnType("uuid");



                            b1.Property<Guid>("QuestionId")

                                .HasColumnType("uuid");



                            b1.HasKey("Id");



                            b1.HasIndex("PerspectiveScenarioExerciseId");



                            b1.ToTable("PerspectiveScenarioAnswers", "practice");



                            b1.WithOwner()

                                .HasForeignKey("PerspectiveScenarioExerciseId");

                        });



                    b.Navigation("Answers");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.PerspectiveScenarios.PerspectiveScenarioQuestion", b =>

                {

                    b.HasOne("AngularNetBase.Practice.Entities.PerspectiveScenarios.PerspectiveScenarioChallenge", null)

                        .WithMany("Questions")

                        .HasForeignKey("PerspectiveScenarioChallengeId")

                        .OnDelete(DeleteBehavior.Cascade)

                        .IsRequired();

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.Sessions.DailySession", b =>

                {

                    b.OwnsOne("AngularNetBase.Practice.Entities.Sessions.MindsetPrimerResult", "PrimerResult", b1 =>

                        {

                            b1.Property<Guid>("DailySessionId")

                                .HasColumnType("uuid");



                            b1.Property<Guid?>("GrowthMessageId")

                                .HasColumnType("uuid")

                                .HasColumnName("PrimerGrowthMessageId");



                            b1.Property<bool>("IsSkipped")

                                .HasColumnType("boolean")

                                .HasColumnName("PrimerIsSkipped");



                            b1.Property<string>("PresentedStatementIds")

                                .IsRequired()

                                .HasColumnType("text")

                                .HasColumnName("PrimerPresentedStatementIds");



                            b1.Property<Guid?>("SelectedStatementId")

                                .HasColumnType("uuid")

                                .HasColumnName("PrimerSelectedStatementId");



                            b1.Property<DateTime>("Timestamp")

                                .HasColumnType("timestamp with time zone")

                                .HasColumnName("PrimerTimestamp");



                            b1.HasKey("DailySessionId");



                            b1.ToTable("DailySessions", "practice");



                            b1.WithOwner()

                                .HasForeignKey("DailySessionId");

                        });



                    b.Navigation("PrimerResult");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.Sessions.SessionEvent", b =>

                {

                    b.HasOne("AngularNetBase.Practice.Entities.Sessions.DailySession", null)

                        .WithMany("Events")

                        .HasForeignKey("DailySessionId")

                        .OnDelete(DeleteBehavior.Cascade)

                        .IsRequired();

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.Skills.Skill", b =>

                {

                    b.OwnsMany("AngularNetBase.Practice.Entities.Skills.SkillLevelDefinition", "Levels", b1 =>

                        {

                            b1.Property<Guid>("Id")

                                .ValueGeneratedOnAdd()

                                .HasColumnType("uuid");



                            b1.Property<string>("Description")

                                .IsRequired()

                                .HasMaxLength(1000)

                                .HasColumnType("character varying(1000)");



                            b1.Property<int>("LevelNumber")

                                .HasColumnType("integer");



                            b1.Property<Guid>("SkillId")

                                .HasColumnType("uuid");



                            b1.Property<string>("Title")

                                .IsRequired()

                                .HasMaxLength(200)

                                .HasColumnType("character varying(200)");



                            b1.HasKey("Id");



                            b1.HasIndex("SkillId");



                            b1.ToTable("SkillLevelDefinitions", "practice");



                            b1.WithOwner()

                                .HasForeignKey("SkillId");

                        });



                    b.Navigation("Levels");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.AffirmationValues.AffirmationValue", b =>

                {

                    b.Navigation("Statements");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.PerspectiveScenarios.PerspectiveScenarioChallenge", b =>

                {

                    b.Navigation("Questions");

                });



            modelBuilder.Entity("AngularNetBase.Practice.Entities.Sessions.DailySession", b =>

                {

                    b.Navigation("Events");

                });

#pragma warning restore 612, 618

        }

    }

}

