// <auto-generated />
using System;
using AngularNetBase.Practice.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AngularNetBase.Practice.Infrastructure.Migrations
{
    [DbContext(typeof(PracticeContext))]
    partial class PracticeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("practice")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AngularNetBase.Practice.Entities.Sessions.DailySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DailySessions", "practice");
                });

            modelBuilder.Entity("AngularNetBase.Practice.Entities.Sessions.SessionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DailySessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DailySessionId");

                    b.ToTable("SessionEvents", "practice");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SessionEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AngularNetBase.Practice.Entities.Sessions.ExerciseRecord", b =>
                {
                    b.HasBaseType("AngularNetBase.Practice.Entities.Sessions.SessionEvent");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Exercise");
                });

            modelBuilder.Entity("AngularNetBase.Practice.Entities.Sessions.GeneralEvent", b =>
                {
                    b.HasBaseType("AngularNetBase.Practice.Entities.Sessions.SessionEvent");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("General");
                });

            modelBuilder.Entity("AngularNetBase.Practice.Entities.Sessions.DailySession", b =>
                {
                    b.OwnsOne("AngularNetBase.Practice.Entities.Sessions.MindsetPrimerResult", "PrimerResult", b1 =>
                        {
                            b1.Property<Guid>("DailySessionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("AffirmationValueId")
                                .HasColumnType("uuid")
                                .HasColumnName("PrimerAffirmationId");

                            b1.Property<Guid?>("GrowthMessageId")
                                .HasColumnType("uuid")
                                .HasColumnName("PrimerGrowthMessageId");

                            b1.Property<bool>("IsSkipped")
                                .HasColumnType("boolean")
                                .HasColumnName("PrimerIsSkipped");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PrimerTimestamp");

                            b1.HasKey("DailySessionId");

                            b1.ToTable("DailySessions", "practice");

                            b1.WithOwner()
                                .HasForeignKey("DailySessionId");
                        });

                    b.Navigation("PrimerResult");
                });

            modelBuilder.Entity("AngularNetBase.Practice.Entities.Sessions.SessionEvent", b =>
                {
                    b.HasOne("AngularNetBase.Practice.Entities.Sessions.DailySession", null)
                        .WithMany("Events")
                        .HasForeignKey("DailySessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AngularNetBase.Practice.Entities.Sessions.DailySession", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
